title: Matt's garage
description: Short description
theme: just-the-docs

collections:
  blog:
    output: true

url: https://mattia-p/mattia-p.github.io

aux_links:
  GitHub:
    - https://github.com/mattia-p
