title: MattNotes
description: Short description
theme: just-the-docs

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

url: https://mattia-p.github.io  # ✅ Fixed your GitHub Pages URL

# Add this section 👇
just_the_docs:
  custom_css:
    - "/assets/css/custom.css"  # GitHub compiles .scss to .css

sass:
  style: compressed  # Optional: makes CSS smaller

aux_links:
  GitHub:
    - https://github.com/mattia-p
