title: MattNotes
description: Short description
theme: just-the-docs

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

url: https://mattia-p/mattia-p.github.io

aux_links:
  GitHub:
    - https://github.com/mattia-p