title: MattNotes
description: Short description
theme: just-the-docs

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  projects:
    output: true
    permalink: /projects/:title/

url: https://mattia-p.github.io

google_analytics: G-192BDE6BDR

aux_links:
  GitHub:
    - https://github.com/mattia-p
